pub mod cas;
pub mod checkpoint;
pub mod compiler;
pub mod context;
pub mod error;
pub mod eval;
pub mod instructions;
pub mod metrics;
pub mod project_index;
mod project_structure;
pub mod protocol;
pub mod remember;
pub mod reranker_eval;
pub mod semantic;
pub mod service;
pub mod store;
pub mod transport;
pub mod update;
pub mod upgrade;

pub use error::{MemoryError, Result};
pub use protocol::{Request, Response};
